--insert into products (price,sku,product_title,quantity) values(100,"Bisk farm biscuits","bisk farm 100",1);
--insert into products (price,sku,product_title,quantity) values(43,"misc","cotton pad",100);
--insert into products (price,sku,product_title,quantity) values(1,"alpenlibe","tofee",100);